[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
darling = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[dev-dependencies]
no_std_io = { path = ".." }
